language: python
addons:
  apt:
    packages:
    - build-essential
before_install:
- export LOCAL="$(mktemp --directory --tmpdir=${TMPDIR:/tmp} local.bin.XXXXXX)"
- export DEP_ZSH_VERSION="zsh-5.0.8"
- curl -L http://downloads.sourceforge.net/zsh/$DEP_ZSH_VERSION.tar.gz | tar zx
- cd $DEP_ZSH_VERSION
- ./configure --prefix=$LOCAL
- make
- make install
- cd -
- export PATH="$LOCAL/bin:$PATH"
install:
- pip install -r test-requirements.txt
- npm install --only=dev
before_script:
- zsh --version
- bash --version
- npm --version
- node --version
script: make test
